pub const IS_RELEASE: bool = false;
pub const DEV_ROOT_PATH: &str = "./";
pub const DEV_DATA_PATH: &str = "../../data/";
pub const RELEASE_ROOT_PATH: &str = "./";
pub const RELEASE_DATA_PATH: &str = "./data/";
pub const DATA_FETCH_INTERVAL: u64 = 10;
pub const DATA_FETCH_TIMING: u64 = 300;
pub const SPREADSHEET_ID: &str = "1CLB6stHi6SdRfjwmuSIhzYUCk4kZXuiv5xXN_nr4JzE";
pub const DISPLAY_SIZE: &str = "4K"; //1
