use crate::config::SPREADSHEET_ID;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FetchSpreadSheetConfig {
    pub sheet_id: &'static str,
    pub fetch_sheet_name: &'static str,
    pub fetch_range: i32,
    pub data_type: &'static str,
    pub graph_pattern: &'static str,
    pub save_graph_data_name: &'static str,
    pub update_interval: i32,
    pub output_sheet_name: &'static str,
    pub output_sheet_range: &'static str,
    pub fetch_range_label: &'static str,
    pub fetch_range_data: &'static str,
    pub fetch_range_target_monthly: &'static str,
    pub fetch_range_target_daily: &'static str,
}

impl FetchSpreadSheetConfig {
    pub fn new() -> Vec<FetchSpreadSheetConfig> {
        vec![
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRS1A",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D4:AC4",
                fetch_range_target_monthly: "B4",
                fetch_range_target_daily: "C4",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRS1S",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D5:AC5",
                fetch_range_target_monthly: "B5",
                fetch_range_target_daily: "C5",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRE",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D6:AC6",
                fetch_range_target_monthly: "B6",
                fetch_range_target_daily: "C6",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRL1T JAC",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D7:AC7",
                fetch_range_target_monthly: "B7",
                fetch_range_target_daily: "C7",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRL3",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D8:AC8",
                fetch_range_target_monthly: "B8",
                fetch_range_target_daily: "C8",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRL2 F2",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D9:AC9",
                fetch_range_target_monthly: "B9",
                fetch_range_target_daily: "C9",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "ASM",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D11:AC11",
                fetch_range_target_monthly: "B11",
                fetch_range_target_daily: "C11",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "FTN",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D12:AC12",
                fetch_range_target_monthly: "B12",
                fetch_range_target_daily: "C12",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "FAS",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D13:AC13",
                fetch_range_target_monthly: "B13",
                fetch_range_target_daily: "C13",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "PW4",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D14:AC14",
                fetch_range_target_monthly: "B14",
                fetch_range_target_daily: "C14",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "その他",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D15:AC15",
                fetch_range_target_monthly: "B15",
                fetch_range_target_daily: "C15",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "SRY2Z",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D17:AC17",
                fetch_range_target_monthly: "B17",
                fetch_range_target_daily: "C17",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "FET",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D18:AC18",
                fetch_range_target_monthly: "B18",
                fetch_range_target_daily: "C18",
            },
            FetchSpreadSheetConfig {
                sheet_id: SPREADSHEET_ID,
                fetch_sheet_name: "生産高",
                fetch_range: 29,
                data_type: "seisan",
                graph_pattern: "combo",
                save_graph_data_name: "monthly_SRS1A_summary_graph_data.js",
                update_interval: 30,
                output_sheet_name: "溶接",
                output_sheet_range: "A1:B1",
                fetch_range_label: "D3:AC3",
                fetch_range_data: "D20:AC20",
                fetch_range_target_monthly: "B20",
                fetch_range_target_daily: "C20",
            },
        ]
    }
}
